### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [rzwibowo/spk-beasiswa#5]
Good day Sir I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before i begin my design. Hoping for your positive feedback. Thanks

**Comment by rzwibowo** [comment]
sure thing, just make a PR

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? which one do you like it ? so that I can immediately make pull requests
![spk](https://user-images.githubusercontent.com/33461607/44416838-3eb0f380-a59e-11e8-858b-428d490f9843.png)

**Comment by mansya** [comment]
I have sent you pull requests. please check. if it's correct I will upload all files to the drive.

**Comment by rzwibowo** [comment]
sorry I haven't touch github for a while. I think, from your suggestion, logo no. 4 would fit nicely in the app.

**Comment by mansya** [comment]
I have upload all files to this drive [**Download**](https://drive.google.com/open?id=1pazpFf0xcNmSm1hL03uuCCL2ILqgtQb1). and I have sent you [**Pull Requests.**](https://github.com/rzwibowo/spk-beasiswa/pull/6) please check it sir.

**Comment by rzwibowo** [comment]
I've merged the PR. thank you for your works, nicely done.
